services:
  web:
    build: .
    command: uvicorn src.app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
      

  worker:
    build: .
    command: celery -A src.workers.tasks worker --loglevel=info
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    depends_on:
      - redis
     

  beat:
    build: .
    command: celery -A src.workers.tasks beat --loglevel=info
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    depends_on:
      - redis
      

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  # db:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_USER: ${postgres_user}
  #     POSTGRES_PASSWORD: ${postgres_password}
  #     POSTGRES_DB: ${postgres_db}
  #   ports:
  #     - "5433:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   env_file:
  #     - .env

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    command: streamlit run src/streamlit_app.py --server.port 8501 --server.address=0.0.0.0
    volumes:
      - ./src:/app/src
    ports:
      - "8501:8501"
    env_file:
      - .env

volumes:
  postgres_data:
